### ISSUE TITLE
Moduł do prestashop 1.6

### ISSUE THREAD

**Issue by Yabbertb** [tpay-com/tpay-prestashop#16]
Dlaczego nie ma modułu do ostatniej stabilnej wersji, czyli prestashop 1.6?
Prestashop 1.7.x i 8.x to nie są aplikacje sklepów, to są typowe wirusy: [https://prestademo.eu.org/pl/content/6-testy-prestashop-17](https://prestademo.eu.org/pl/content/6-testy-prestashop-17)

**Comment by kwojc** [comment]
Dzień dobry,

Polegamy wyłącznie na danych pochodzących od autorów rozwiązań i nie sugerujemy się informacjami z niesprawdzonych źródeł. 

Aktualnie PrestaShop 1.6 jest już niewspierana, więc i my aktywnie nie wspieramy tej wersji sklepu - mamy natomiast archiwalną wersję naszego starego modułu, który nadal działa - https://github.com/tpay-com/tpay-prestashop-legacy

Pozdrawiam
